### ISSUE TITLE
CI Builds unable to pull image

### ISSUE THREAD

**Issue by dillon-giacoppo** [jfrog/jfrog-distroless#4]
CI Builds are failing with 6.10.1 due to `failed to register layer: Error processing tar file(exit status 1): Container ID 321851968 cannot be mapped to a host ID`. This happens because the UID is too high for some files.

The image fails to pull in a multi-stage build because of this in Bitbucket Pipelines. https://docs.docker.com/engine/security/userns-remap/ and
https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-make-your-containers-more-secure-on-Bitbucket/ba-p/998464#M89

This problem is not localised to Bitbucket Pipelines, other CI tools like CircleCI have the same security settings:
https://circleci.com/docs/2.0/high-uid-error/

It looks like the affected files in particular are related to the JDK installation. Running `find / -user 321851968 2>/dev/null`.

**Comment by dillon-giacoppo** [comment]
Looks like it is related to https://github.com/jfrog/artifactory-docker-examples/issues/153.

**Comment by PtyMatt** [comment]
@dillon-giacoppo yes still the same problem :(

**Comment by eldada** [comment]
A version with the fix is planned to be released in the near future.

**Comment by PtyMatt** [comment]
It's now good for me since version 6.10.4 :+1:

**Comment by arturo-aparicio** [comment]
Marking as closed due to previous comments. If you run into this, feel free to open a new issue.
